language: generic
sudo: required #Tells TravisCI you need super user level permissions in order to execute this build
services:
  - docker #Makes sure that TravisCI understands that we need the Docker CLI pre-installed, by adding this in TravisCI is going to automatically install a copy of Docker into your container
 
before_install: #This section is going to have a series of different commands that get executed before our tests are ran
  - docker build -t chennat234/docker-react -f Dockerfile.dev . #Tells TravisCI to build our docker image before the tests run. | "." means use the current directory when figruing what to do

script: #Used to contain all the different commands that need to be executed to actually run our test suite | #unlike before_install these commands ar going to run when our tests need to actually be executed
  - docker run -e CI=true chennat234/docker-react npm run test #TravisCI watches the output of each of this commands and from each command if it gets a return status other than 0 Travis will assume that our build failed or that our tests failed to run properly. And then will assume that our code is essentially broken.

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1" 
  bucket_name: "elasticbeanstalk-us-east-1-371868300721"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
