language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t chennat234/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chennat234/docker-react npm run test
